### ISSUE TITLE
feat : add exclude option to right click menu

### ISSUE THREAD

**Issue by tjex** [RedHotRojo/Dark-Mode-Screen#10]
It would be really great to have the option to exclude a page available by right clicking on the page itself and selecting from the right click context menu, like page blocker/1pass/zotero as seen below.

This is because when using a laptop, the middle click is not available (albeit without some accessibility hot key or something.

![Screen Shot 2023-02-03 at 09 50 37](https://user-images.githubusercontent.com/83029642/216554550-5fd2bced-b948-4a5e-8de4-94aff6b5e5d0.png)

**Comment by RedHotRojo** [comment]
Great idea! I'll start working on it soon
