### ISSUE TITLE
flashing while loading site

### ISSUE THREAD

**Issue by Monirzadeh** [RedHotRojo/Dark-Mode-Screen#12]
Hi,
i test this extension and it flashing while website loading.
i understand it is not load cover at the beginning of stile loading but it not happen with other extension (or more less) like [Dark View](https://addons.mozilla.org/en-US/firefox/addon/darkview/).
is there any way to improve that

**Comment by RedHotRojo** [comment]
Fixed with new version. Let me know if you're satisfied with the load speed.
