### ISSUE TITLE
Settings inaccessible: File not found.

### ISSUE THREAD

**Issue by mzso** [RedHotRojo/Dark-Mode-Screen#6]
Hi!

I just tried this addon in FF97. There's settings tab in about:config for the addon, but it doesn't load.

Not possible to change settings.

**Comment by RedHotRojo** [comment]
Yeah, I don't really know why it still shows a settings tab. You can change the settings by middle-clicking the toolbar icon.

**Comment by RedHotRojo** [comment]
I have removed the settings tab in v1.8.5
