### ISSUE TITLE
Values alwasy reset to default setting 

### ISSUE THREAD

**Issue by Moonay-TeamCoffee** [RedHotRojo/Dark-Mode-Screen#9]
Hello,
I've been using the plugin for some time, and there's something that's been bugging me, Each time I turn off the dark mode it seem to reset to default values (_R-36 ; G-34 ; B-33 ; A-40_) and I want to set the RGB values to 0 every time since I only want to darken the screen, but it does not stay, 
Every time I open the menu box of the plugin : the values have reset to default, 
This also happens when the dark mode is already enabled with different settings, if so, then moving any of the sliders will update the screen back to the default color, this is especially problematic because between different websites and tabs I might need to adjust the value of the Alpha just a little, but since the default value comes back ... I need to readjust all the sliders instead.

Plugin Version : 1.9
Firefox Version : 102.5.0esr (64-bit) Linux
Current OS : Debian 11 Bullseye (64-bit)

**Comment by Moonay-TeamCoffee** [comment]
I have here a screen recording of the problem, all other features of the plugin work as I imagine they are intended :
[Screencast from 11-23-2022 08:12:13 PM.webm](https://user-images.githubusercontent.com/118878748/203629095-ab77cf65-f3c7-4678-b66a-a8fbe3c33661.webm)

**Comment by RedHotRojo** [comment]
> I have here a screen recording of the problem, all other features of the plugin work as I imagine they are intended : [Screencast from 11-23-2022 08:12:13 PM.webm](https://user-images.githubusercontent.com/118878748/203629095-ab77cf65-f3c7-4678-b66a-a8fbe3c33661.webm)

Thanks for extra info. I'll start working on this issue soon.

**Comment by RedHotRojo** [comment]
After reproducing it on my Kali Linux laptop, I was able to fix it. I wasn't using Firefox ESR, but that shouldn't make a difference. Let me know if you are still facing this issue.

**Comment by Moonay-TeamCoffee** [comment]
Updated to 1.9.1 and confirmed ; bug fixed
Also re-verified all features, everything seems to be functioning as intended.
Thank you for the fix.
